import { useEffect, useState } from 'react';
import { CheckCircle2, Lock, Play, Pause, Server } from 'lucide-react';
type Pillar = 'C' | 'I' | 'A';
const details: Record<Pillar, { name: string; command: string; result: string }> = {
  C: { name: 'Confidentiality', command: 'TLS record encrypted → unauthorized reader receives ciphertext', result: 'Access granted only after identity verification.' },
  I: { name: 'Integrity', command: 'SHA-256 digest recomputed → payload change detected', result: 'Modified record is rejected before processing.' },
  A: { name: 'Availability', command: 'Primary service unavailable → health check directs traffic to standby', result: 'Requests continue through the healthy service.' },
};
export function CiaTriadViz() {
  const [pillar, setPillar] = useState<Pillar>('C'); const [playing, setPlaying] = useState(true);
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setPillar((value) => value === 'C' ? 'I' : value === 'I' ? 'A' : 'C'), 3200); return () => window.clearInterval(timer); }, [playing]);
  const detail = details[pillar]; const Icon = pillar === 'C' ? Lock : pillar === 'I' ? CheckCircle2 : Server;
  return <div className="space-y-5 font-mono select-none w-full">
    <div className="flex items-center justify-between gap-3 p-3 rounded-lg bg-[#F7F7F7] dark:bg-[#141414] border border-[#E5E5E5] dark:border-[#2A2A2A]"><div className="flex gap-1.5 overflow-x-auto">{(['C', 'I', 'A'] as Pillar[]).map((item) => <button key={item} type="button" onClick={() => { setPillar(item); setPlaying(false); }} className={`px-3 py-1.5 text-xs font-bold uppercase border transition-colors ${pillar === item ? 'bg-[#111111] dark:bg-white text-white dark:text-[#080808] border-[#111111] dark:border-white' : 'bg-white dark:bg-[#181818] text-[#666666] dark:text-[#B5B5B5] border-[#E5E5E5] dark:border-[#2A2A2A]'}`}>{item} · {details[item].name}</button>)}</div><button type="button" onClick={() => setPlaying(!playing)} className="p-2 border border-[#E5E5E5] dark:border-[#2A2A2A] bg-white dark:bg-[#181818] text-[#111111] dark:text-white"><span className="sr-only">{playing ? 'Pause' : 'Play'}</span>{playing ? <Pause size={14} /> : <Play size={14} />}</button></div>
    <div className="rounded-lg border border-[#E5E5E5] dark:border-[#2A2A2A] bg-white dark:bg-[#101010] p-5 sm:p-7 overflow-hidden"><div className="grid grid-cols-1 sm:grid-cols-[1fr_auto_1fr] gap-4 items-center min-h-[180px]"><div className="border border-[#E5E5E5] dark:border-[#2A2A2A] p-4 bg-[#F7F7F7] dark:bg-[#181818]"><p className="text-[10px] text-[#888888] dark:text-[#777777] font-bold uppercase">Request origin</p><p className="text-sm font-extrabold text-[#111111] dark:text-white mt-1">CLIENT REQUEST</p></div><div className="hidden sm:flex items-center gap-2 text-[#111111] dark:text-white"><span className="h-px w-8 bg-current opacity-40" /><Icon size={22} className={playing ? 'cia-concept-flow' : ''} /><span className="h-px w-8 bg-current opacity-40" /></div><div className="border border-[#111111] dark:border-white p-4 bg-white dark:bg-[#141414]"><p className="text-[10px] text-[#888888] dark:text-[#777777] font-bold uppercase">Control result</p><p className="text-sm font-extrabold text-[#111111] dark:text-white mt-1">{pillar === 'A' ? 'STANDBY SERVICE' : pillar === 'I' ? 'VERIFIED RECORD' : 'AUTHORIZED SESSION'}</p></div></div><div className="mt-5 pt-4 border-t border-[#E5E5E5] dark:border-[#2A2A2A]"><p className="text-xs font-bold text-[#111111] dark:text-white">{detail.command}</p><p className="text-xs text-[#666666] dark:text-[#B5B5B5] font-sans mt-2">{detail.result}</p></div></div>
  </div>;
}
